### ISSUE TITLE
To be able to edit the published bundle

### ISSUE THREAD

**Issue by hash9** [kunalmhatre/bundlem#26]
## Comments and feature request
Bundlem is very clean and does the job perfectly. A short request, If only we could edit the bundle too.

## Why for suggested request
Since a bundle created has a unique bundle id and it contains all the resources for the same, may be in the near future if the user wants to edit the resource/info in the same bundle, he/she might want to edit the same bundle.

**Comment by kunalmhatre** [comment]
Hey Harshit, thanks for the feature request. To be honest, I had a plan to introduce that particular feature in v2.0.0. But, as the current codebase and development approach is not that scalable, I have taken that into priority for v2.0.0 and here is the issue for that #25. That being said, the feature to edit bundles will take good amount of time because of the planning involved over authentication and authorisation of the user. Also, the main reason for deferring this feature for now is the user engagement, which is almost null for this service. :sweat_smile:

I am closing this issue for now, but if I decide to work on this feature later, I will surely re-open it and let you know about it. Thank you again. :smile:
